apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hr-service-cluster
  region: us-west-2

nodeGroups:
  - name: hr-service-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true

# Enable logging
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
