apiVersion: v1
kind: Service
metadata:
  name: hr-service
  labels:
    app: hr-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: hr-service
