apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrsite-frontend
  namespace: hrsite
  labels:
    app: hrsite-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hrsite-frontend
  template:
    metadata:
      labels:
        app: hrsite-frontend
    spec:
      containers:
      - name: hrsite-frontend
        image: 176448595866.dkr.ecr.us-east-1.amazonaws.com/hrsite-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hrsite-frontend
  namespace: hrsite
  labels:
    app: hrsite-frontend
spec:
  selector:
    app: hrsite-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
